import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import SnowfallEffect from "./Components/SnowfallEffect";
import MagicFooter from "./Components/footer";

// Admin Config - Change this value to enable/disable snowfall
export const SNOWFALL_ENABLED = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0a0a] `}
      >
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <MagicFooter />
        {SNOWFALL_ENABLED && <SnowfallEffect />}
      </body>
    </html>
  );
}
